### ISSUE TITLE
Docker file request

### ISSUE THREAD

**Issue by juhonkang** [cuhk-eda/cu-gr#3]
Hi, I respect your work.
Could you give the community a Docker file to easily reproduce your results?
Thanks a lot!

**Comment by Rholais** [comment]
Thanks for raising the issue.
Have you encountered any difficulties reproducing the results?

**Comment by Rholais** [comment]
@juhonkang  I will close the issue if there is no other problem regarding compilation

**Comment by juhonkang** [comment]
Sorry for not getting back to you.
Yes, please close it, thanks!
